# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/likewise-open/SENSETIME/xumingchao/Documents/experiments/cv_homework/sift

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/likewise-open/SENSETIME/xumingchao/Documents/experiments/cv_homework/sift

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/likewise-open/SENSETIME/xumingchao/Documents/experiments/cv_homework/sift/CMakeFiles /home/likewise-open/SENSETIME/xumingchao/Documents/experiments/cv_homework/sift/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/likewise-open/SENSETIME/xumingchao/Documents/experiments/cv_homework/sift/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sift

# Build rule for target.
sift: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sift
.PHONY : sift

# fast build rule for target.
sift/fast:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/build
.PHONY : sift/fast

jpeg.o: jpeg.c.o
.PHONY : jpeg.o

# target to build an object file
jpeg.c.o:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/jpeg.c.o
.PHONY : jpeg.c.o

jpeg.i: jpeg.c.i
.PHONY : jpeg.i

# target to preprocess a source file
jpeg.c.i:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/jpeg.c.i
.PHONY : jpeg.c.i

jpeg.s: jpeg.c.s
.PHONY : jpeg.s

# target to generate assembly for a file
jpeg.c.s:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/jpeg.c.s
.PHONY : jpeg.c.s

jpg.o: jpg.c.o
.PHONY : jpg.o

# target to build an object file
jpg.c.o:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/jpg.c.o
.PHONY : jpg.c.o

jpg.i: jpg.c.i
.PHONY : jpg.i

# target to preprocess a source file
jpg.c.i:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/jpg.c.i
.PHONY : jpg.c.i

jpg.s: jpg.c.s
.PHONY : jpg.s

# target to generate assembly for a file
jpg.c.s:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/jpg.c.s
.PHONY : jpg.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/main.c.s
.PHONY : main.c.s

mat.o: mat.c.o
.PHONY : mat.o

# target to build an object file
mat.c.o:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/mat.c.o
.PHONY : mat.c.o

mat.i: mat.c.i
.PHONY : mat.i

# target to preprocess a source file
mat.c.i:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/mat.c.i
.PHONY : mat.c.i

mat.s: mat.c.s
.PHONY : mat.s

# target to generate assembly for a file
mat.c.s:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/mat.c.s
.PHONY : mat.c.s

sift.o: sift.c.o
.PHONY : sift.o

# target to build an object file
sift.c.o:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/sift.c.o
.PHONY : sift.c.o

sift.i: sift.c.i
.PHONY : sift.i

# target to preprocess a source file
sift.c.i:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/sift.c.i
.PHONY : sift.c.i

sift.s: sift.c.s
.PHONY : sift.s

# target to generate assembly for a file
sift.c.s:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/sift.c.s
.PHONY : sift.c.s

type.o: type.c.o
.PHONY : type.o

# target to build an object file
type.c.o:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/type.c.o
.PHONY : type.c.o

type.i: type.c.i
.PHONY : type.i

# target to preprocess a source file
type.c.i:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/type.c.i
.PHONY : type.c.i

type.s: type.c.s
.PHONY : type.s

# target to generate assembly for a file
type.c.s:
	$(MAKE) -f CMakeFiles/sift.dir/build.make CMakeFiles/sift.dir/type.c.s
.PHONY : type.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sift"
	@echo "... jpeg.o"
	@echo "... jpeg.i"
	@echo "... jpeg.s"
	@echo "... jpg.o"
	@echo "... jpg.i"
	@echo "... jpg.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mat.o"
	@echo "... mat.i"
	@echo "... mat.s"
	@echo "... sift.o"
	@echo "... sift.i"
	@echo "... sift.s"
	@echo "... type.o"
	@echo "... type.i"
	@echo "... type.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

